"""create queries table

Revision ID: 1896d5057843
Revises: 
Create Date: 2025-10-14 12:55:03.810248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1896d5057843'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queries_id'), table_name='queries')
    op.drop_table('queries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('input_location', sa.VARCHAR(), nullable=False),
    sa.Column('resolved_name', sa.VARCHAR(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=False),
    sa.Column('lon', sa.FLOAT(), nullable=False),
    sa.Column('kind', sa.VARCHAR(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('result_payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_id'), 'queries', ['id'], unique=False)
    # ### end Alembic commands ###
